name: Docker CI/CD

on:
  push: 
    branches: ["ci-demo"]
  pull_request:
    branches: ["master"]
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run production build script
        run: npm run build:env.production

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTIFY_PROVIDER }}
      - name: Describe account
        run: gcloud iam service-accounts describe ${{ secrets.GCP_SERVICE_ACCOUNT }}
