# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docker CI/CD

on:
  push: 
    branches: ["ci-demo"]
  pull_request:
    branches: ["master"]
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
- uses: actions/checkout@v3

      - name: Run production build script
        run: npm run build:env.production

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: {{ secrets.GCP_PROJECT_ID }}
          service_account: {{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: {{ secrets.GCP_WORKLOAD_IDENTIFY_PROVIDER }}
      - name: Describe account
        run: gcloud iam service-accounts describe {{ secrets.GCP_SERVICE_ACCOUNT }}
